#!/usr/bin/env sh

# load scripting addition (requires SIP partially disabled)
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# make sure jq is available in launchd context
export PATH=/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH

# === global settings ===
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow off
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

yabai -m config window_animation_duration 0.12
yabai -m config window_animation_easing ease_in_out_cubic
borders style=round width=6.0 active_color=0xffe1e3e4 inactive_color=0xff494d64 &

# opacity + animations
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.00
yabai -m config normal_window_opacity 0.95
yabai -m config window_opacity_duration 0.12
yabai -m signal --add label=flash_focus event=window_focused action='yabai -m window --opacity 0.90; sleep $(yabai -m config window_opacity_duration); yabai -m window --opacity 1.0'
yabai -m config focus_follows_mouse autofocus

# borders
yabai -m config window_border on
yabai -m config window_border_width 3
yabai -m config active_window_border_color 0xffa6e3a1
yabai -m config normal_window_border_color 0xff6c7086
yabai -m config insert_feedback_color 0xffd75f5f

# mouse interactions
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# === space defaults ===
# --- Layout & spacing ---
yabai -m config layout bsp
yabai -m config window_gap 12
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8

# === rules ===
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pika$" manage=off
yabai -m rule --add app="^balenaEtcher$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Shottr$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off

# bar space (keep at 0 if no bar)
#yabai -m config external_bar all:0:0
# === signals ===
yabai -m signal --add event=space_changed action="sketchybar --trigger space_change"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_changed action="sketchybar --trigger display_change"
yabai -m config external_bar all:$(sketchybar --query bar | jq .height):0
echo "yabai configuration loaded.."
